### ISSUE TITLE
Create Registration Form

### ISSUE THREAD

**Issue by Carlomos7** [Carlomos7/IT490-002#19]
- Start in `git checkout sampleweb` and pull the latest changes: `git pull origin sampleweb`
- Create a new branch from "sampleweb": `git checkout -b feat-simple-registration-form`. 
(the `-b` flag creates the branch you are trying to checkout)
- Create a simple register form that takes in a username, password, and confirm password in the [register.php](https://github.com/Carlomos7/IT490-002/blob/sampleweb/register.php). Refer to the form from the [login](https://github.com/Carlomos7/IT490-002/blob/sampleweb/index.php) ~should be more or less the same form
- Make sure to require the nav bar from partials at the top ( this is just like in the index.php). It contains the CSS to make everything all pretty
- Once complete check the status of the modified file `git status`
- Add the modified file to be tracked by git `git add <filename>` or just `git add .` (**this adds all modified files**)
- Commit the file to the to your feature branch `git commit -m "<short and concise msg describing the change"`
- Push your local change from the branch to remote (GitHub) `git push origin <branch-name>` 
- Create pull request to merge your feature branch into **sampleweb** and resolve any conflicts
- Navigate to this issue and under **Development** select the feature branch you just merged then close the issue
- On your local, checkout **sampleweb** (`git checkout sampleweb`) and pull the changes from remote `git pull origin sampleweb`
- Lastly, close this issue and add a comment explaining your steps at a high level along with a screenshot of your relevant work (try to do the best you can for now, in the future, we'll need this to present our documentation for our final & midterm)

**Comment by LuandaS** [comment]
Made the from for the registration page 
![Screen Shot 2023-02-16 at 10 00 48 PM](https://user-images.githubusercontent.com/113204714/219538813-b09b260d-2c21-46d3-84e5-8e909e0f6191.png)
