### ISSUE TITLE
Registration form submission

### ISSUE THREAD

**Issue by Carlomos7** [Carlomos7/IT490-002#21]
- Start in `git checkout sampleweb` and pull the latest changes: `git pull origin sampleweb`
- Create a new branch from "sampleweb": `git checkout -b feat-register`. 
(the `-b` flag creates the branch you are trying to checkout)
- In register.php under the registration form start the server side validaiton in php. It'll start with `if (isset($_POST['submit'])){}`
- Refer to [index.php](https://github.com/Carlomos7/IT490-002/blob/sampleweb/index.php) starting at line 22 for the following
1. You'll need to grab the username, pass, and confirm from the POST array 
2. Open a rabbitMQclient connection
3. Create a registration array
4. Give it a type of `register`, pass in username, password, confirm, and a msg describing the request ~ `Sending register request`
5. Send the $register_req as a request
6. Create a switch case for for the response from the server base it off the returns for [lib/handleRegster.php](https://github.com/Carlomos7/IT490-002/blob/sampleweb/lib/handleRegister.php)
- Once complete check the status of the modified file `git status`
- Add the modified file to be tracked by git `git add <filename>` or just `git add .` (**this adds all modified files**)
- Commit the file to the to your feature branch `git commit -m "<short and concise msg describing the change"`
- Push your local change from the branch to remote (GitHub) `git push origin <branch-name>` 
- Create pull request to merge your feature branch into **sampleweb** and resolve any conflicts
- Navigate to this issue and under **Development** select the feature branch you just merged then close the issue
- On your local, checkout **sampleweb** (`git checkout sampleweb`) and pull the changes from remote `git pull origin sampleweb`
- Lastly, close this issue and add a comment explaining your steps at a high level along with a screenshot of your relevant work (_try to do the best you can for now, in the future, we'll need this to present our documentation for our final & midterm_)

**Comment by jaylincabrera10** [comment]
![image](https://user-images.githubusercontent.com/98345193/219694699-7de3988c-9531-473c-8016-b5ca04fbb491.png)

Made changes to register.php, grabbed user/pass/confirm fields from form, created register array, sent received form responses to rabbitMQ, implemented switch statement to check whether register was success/failure.
