### ISSUE TITLE
Simple Server Register Valdiation

### ISSUE THREAD

**Issue by Carlomos7** [Carlomos7/IT490-002#30]
Add some simple server validation (php) to register.php to check the following:
- username is not empty
- Password is not empty
- confirm is not empty && password and confirm are equal

Use a variable (e.g., `$hasError`) to keep track of the changes. It shoud be set to true _if_* any of the above validation is true

If there is an error then make sure to give the user a user friendly message letting them know the exact issue

Then if there are no errors get the rabbit client connection, register array, send request, and switch case for the response.

**Comment by jaylincabrera10** [comment]
![image](https://user-images.githubusercontent.com/98345193/219721081-297e4354-6f97-4246-82dc-0f8ba0c90187.png)

Made changes to register.php, added server validation code, created register array, sending values to rabbitMQ.
