### ISSUE TITLE
feat-email_form

### ISSUE THREAD

**Issue by Carlomos7** [Carlomos7/IT490-002#49]
### Issue Summary
Add an email to the register.php form and validate it (only make changes to register's form)

### Problem Statement
We need an email entry for each user registered

### Benefits
Users can log in with the email and receive email updates and authentication codes (eventually)

**Comment by jmpearson135** [comment]
Added email to the register form 
![image](https://user-images.githubusercontent.com/123332874/222039872-80c01600-4ab4-447d-8fc6-f75f91f9f3d1.png)

- Added a new div section and put a label and text box so the user can register an email address.

![image](https://user-images.githubusercontent.com/123332874/222040230-72284911-658f-4e60-ad71-5185172d3bdd.png)

- Added email variable that gets the user's email address when the form is submitted via POST.

![image](https://user-images.githubusercontent.com/123332874/222039907-bf83b36d-fd37-462b-bbb9-0bdef4653a51.png)

- Checked to see if the email textbox is empty (will add further validation using regex later).
