### ISSUE TITLE
John - Test github basics

### ISSUE THREAD

**Issue by Carlomos7** [Carlomos7/IT490-002#7]
###  Git Cheat Sheet
- Switch branches `git checkout main`
- Pull the latest changes from remote `git pull origin main`
- Create a branch `git checout -b feat-<name>`
- Check the status of tracked files `git status`
- Track the changed files `git add . ` or `git add <file_name>`
- Commit changes `git commt -m "<msg>"`
- Push changes from local to remote `git push origin feat-<name>`
- Create & Merge the the pull request in GitHub, i.e., main <- feat<name>
- Checkout main `git checkout main`
- Pull changes from remote to local `git pull origin main`

**Comment by jmpearson135** [comment]
Followed instructions and completed everything.
